### PR TITLE
Reorganize Provision Docs

### PR DESCRIPTION
**Pull request by Azdle**
This is a fairly substantial change so I thought I should make this a PR and let a couple people verify that I didn't screw anything up.

Calling @dweaver @maanenson @emdv

Since the static site generator stuff is new, you can view the rendered version with `gulp serve`.

If you don't have node installed, run this in the cloned directory:
```
brew install node
npm install -g gulp
npm install
gulp serve
```

### CODE REVIEW

**Comment by EmDV** [comment]
#### Feedback for the new HTTP API page
* It might be useful to include a link to the new HTTP page '/http' to help guide users that become aware of the new change|merge. Hopefully this would live just under the CoAP link within 'Device APIs'. Rationale: Once I knew that the new documentation lived in a different path, it was annoying to keep having to click on the depcrecated pages to get to the proper link.
* We might want to include a link to the Long-Polling example in the new page(http), or combine it as a large example under 'Read'. It is jarring to find the Long-Polling example without a link and treated as a separate procedure. 
* On the IP procedure we have a note that reads "Depreciated, use DNS instead.", I am a newb but my understanding was that depcreciated relates to value and deprecated relates to non-recommended software usage. 

#### Possible Improvement for CoAP doc Page
* Include links to the same page similair in spirit as the HTTP API documenation. E.g. 'Write - write new data to a set of dataports', <name of procedure> - <descrption of procedure>

**Comment by EmDV** [comment]
Oops I left one other thing out!

* Under the newly merged Provisioning Procedures we forgot to include out standard link to 'See HTTP Responses for a full list of responses.' To point them to the table of responses that are not idiomatic or expected.

**Comment by Azdle** [comment]
@EmDV I've made all the changes that you suggested, except I left the long-polling separate, I just moved it into the 'data procedures' section. Do you think that is enough?

**Comment by EmDV** [comment]
Cool beans, looks good.

**Pull request merged**
