### PR TITLE
Use "Core Services" Term

### PR DESCRIPTION
**Pull request by chadandycha**
Wording changed to "Core Services" 
Note: there are other changes to this document that have not been made live yet. Are these changes intended to go live?

### CODE REVIEW

**Comment by azdle** [comment]
I'll merge this as-is since it's a trivial change, but are we going to use this term anywhere else, or make any references to non-core services? @chadandycha

**Comment by chadandycha** [comment]
I was instructed as follows: "Eventually, we'll distinguish core services, professional tier services, and enterprise services. But for now, we just have Core Services. Please add the word "Core" in front of "Services" here:
http://docs.exosite.com/murano/services/"

Is the link above the correct location for this doc that was updated?

**Comment by azdle** [comment]
Okay, it looks like the build & fetch script overwrites this file when it runs. It looks like the only way to get this change made would be to have @sauvainr copy it over into the actual server repo.

**Comment by sauvainr** [comment]
Hi, yes this page comes from this file:
https://github.com/exosite/pegasus_registry/blob/master/api/mocks/md/docPage.ejs
I added the 'Core'.

**Pull request merged**
