### PR TITLE
Add scripting log doc

### PR DESCRIPTION
**Pull request by sauvainr**
Added brief script troubleshooting chapter to scripting doc with details regarding the logs.

### CODE REVIEW

**Comment by azdle** [comment]
Sorry for missing this earlier. There are a few grammar fixes I'd like to make, but I want you to review anything I change to make sure I'm not changing any meaning. I'll merge this as-is for now.

**Comment by azdle** [comment]
Also, @sauvainr, I didn't notice this before I did the merge, but all docs work should be against master now.

**Comment by sauvainr** [comment]
Thanks @azdle should I redo make to PR to master?

**Comment by azdle** [comment]
@sauvainr, already merged it myself: #37

**Pull request merged**
